# Generated by Django 5.2.5 on 2025-12-10 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('bidirectional', models.BooleanField(default=True)),
                ('from_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='optimizer.location')),
                ('to_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='optimizer.location')),
            ],
        ),
    ]
